path: /data/i3store/users/tstjean/data/backend/test_minimal/merged/merged.db
graph_definition:
  arguments:
    columns: [0, 1, 2]
    detector:
      arguments: {}
      class_name: ModORCA150SuperDense
    dtype: torch.float32
    nb_nearest_neighbours: 8
    node_definition:
      arguments: {}
      class_name: NodesAsPulses
    input_feature_names:
      - dom_x
      - dom_y
      - dom_z
      - dom_time
  class_name: KNNGraph
pulsemaps:
  - InIceDSTPulses
features:
  - dom_x
  - dom_y
  - dom_z
  - dom_time
truth:
  - energy
  - position_x
  - position_y
  - position_z
  - azimuth
  - zenith
  - pid
  - event_time
  - sim_type
  - interaction_type
  - elasticity
  - RunID
  - SubrunID
  - EventID
  - SubEventID
  - dbang_decay_length
  - track_length
  - stopped_muon
  - energy_track
  - energy_cascade
  - inelasticity
  - DeepCoreFilter_13
  - CascadeFilter_13
  - MuonFilter_13
  - OnlineL2Filter_17
  - L3_oscNext_bool
  - L4_oscNext_bool
  - L5_oscNext_bool
  - L6_oscNext_bool
  - L7_oscNext_bool
  - is_starting
  - event_no
index_column: event_no
truth_table: truth
seed: 21
selection:
  train: event_no % 5 > 1
  validation: event_no % 5 == 1
  test: event_no % 5 == 0
